image:
  file: .gitpod.dockerfile
tasks:
  - name: Continuous Build
    command: yarn global add concurrently && go install github.com/cosmtrek/air@latest && cd /workspace/xbvr && go generate && go get && yarn && yarn dev
ports:
  - port: 9999
    onOpen: open-preview
  - port: 1338
    onOpen: ignore
  - port: 9998
    onOpen: ignore
