before:
  hooks:
    - go mod download
    - go generate ./...

builds:
- id: xbvr-windows
  binary: xbvr
  main: pkg/tray/main.go
  flags:
    - -tags=json1
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}} -H windowsgui
  env:
    - CGO_ENABLED=1
    - CC=x86_64-w64-mingw32-gcc
    - CXX=x86_64-w64-mingw32-g++
  goos:
    - windows
  goarch:
    - amd64

dockers:
  -
    use: buildx
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/{{.Env.GITHUB_USER}}/{{.Env.GITHUB_PROJECT}}:{{ .Version }}-amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --no-cache
      - --label=org.opencontainers.image.source=https://github.com/{{.Env.GITHUB_USER}}/{{.Env.GITHUB_PROJECT}}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}

docker_manifests:
  - name_template: ghcr.io/{{.Env.GITHUB_USER}}/{{.Env.GITHUB_PROJECT}}:{{ .Version }}
    image_templates:
      - ghcr.io/{{.Env.GITHUB_USER}}/{{.Env.GITHUB_PROJECT}}:{{ .Version }}-amd64
  - name_template: ghcr.io/{{.Env.GITHUB_USER}}/{{.Env.GITHUB_PROJECT}}:latest
    image_templates:
      - ghcr.io/{{.Env.GITHUB_USER}}/{{.Env.GITHUB_PROJECT}}:{{ .Version }}-amd64

archives:
- id: archive-win
  builds:
    - xbvr-windows
  format: zip
  replacements:
    windows: Windows
#  files:
#    - XBVR.app/Contents/Resources/XBVR.icns
#    - XBVR.app/Contents/Info.plist

snapshot:
  name_template: "{{ .Tag }}-next"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Scrapers'
      regexp: "^.*scrapers?[(\\w)]*:+.*$"
      order: 1
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
    - "^docs:"
    - "^minor:"
    - "^test:"

release:
  disable: false
